[package]
name = "tauri-update-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
serde = "1.0"
lru_time_cache = "0.11.11"
serde_json = "1.0"
either = "1.8"
